#deployment.yaml
#namespace: devops-rocket 
replicaCount: 1
image:
  repository: saranya99/helm
  tag: v1
containerPort: 80
# service.yaml
service:
  port: 80
  targetPort: 80
  containerPort: 80
  nodePort: 30009
  type: NodePort
