#deployment.yaml
#namespace: devops
replicaCount: 0
image:
  repository: saranya99/helm
  tag: v1
containerPort: 80
# service.yaml
service:
  port: 80
  targetPort: 80
  containerPort: 80
  nodePort: 30008
  type: NodePort
